# render.yaml - Render Blueprint Specification
# https://docs.render.com/blueprint-spec

services:
  - type: web
    name: django-portfolio
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn ProjectPortfolio.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
